Repository apache/uima-uimafit, pull requests merged in 2020-04, with the labels that each got.

#91 UIMA 6181 - fix complaints about maven plugin plugin in eclipse
  pom.xml
  uimafit-benchmark/pom.xml
  uimafit-core/pom.xml
  uimafit-cpe/pom.xml
  uimafit-docbook/pom.xml
  uimafit-examples/pom.xml
  uimafit-maven-plugin/pom.xml
  uimafit-parent/pom.xml
  uimafit-spring/pom.xml
Labels: refactoring

#92 [UIMA-6147] Upgrade to spring 4
  NOTICE
  src/main/dist-bin/LICENSE
  src/main/dist-bin/NOTICE
  uimafit-benchmark/pom.xml
  uimafit-core/.settings/org.eclipse.jdt.core.prefs
  uimafit-cpe/.settings/org.eclipse.core.resources.prefs
  uimafit-cpe/.settings/org.eclipse.jdt.core.prefs
  uimafit-cpe/pom.xml
  uimafit-examples/.settings/org.eclipse.jdt.core.prefs
  uimafit-legacy-support/.settings/org.eclipse.jdt.core.prefs
  uimafit-maven-plugin/.settings/org.eclipse.jdt.core.prefs
  uimafit-parent/pom.xml
  uimafit-spring/.settings/org.eclipse.jdt.core.prefs
Labels: refactoring

#95 [UIMA-6216] Upgrade to UIMA Core 3.1.1
  src/main/dist-bin/NOTICE
  uimafit-parent/pom.xml
Labels: refactoring

#96 [UIMA-5847] Remove uv3 bug workarounds in fs collection factory
  README
  uimafit-core/src/main/java/org/apache/uima/fit/util/FSCollectionFactory.java
  uimafit-cpe/.settings/org.eclipse.core.resources.prefs
Labels: refactoring

#97 [UIMA-6214] Method signature clash in external resource factory
  README
  pom.xml
  uimafit-core/src/main/java/org/apache/uima/fit/component/ExternalResourceAware.java
  uimafit-core/src/main/java/org/apache/uima/fit/factory/AnalysisEngineFactory.java
  uimafit-core/src/main/java/org/apache/uima/fit/factory/CollectionReaderFactory.java
  uimafit-core/src/main/java/org/apache/uima/fit/factory/ExternalResourceFactory.java
  uimafit-core/src/main/java/org/apache/uima/fit/factory/FlowControllerFactory.java
  uimafit-core/src/test/java/org/apache/uima/fit/factory/AnalysisEngineFactoryExternalResourceTest.java
  uimafit-core/src/test/java/org/apache/uima/fit/factory/ExternalResourceFactoryTest.java
  uimafit-docbook/src/docbook/tools.uimafit.migration.xml
  uimafit-spring/src/test/java/org/apache/uima/fit/spring/SpringContextResourceManagerTest.java
Labels: bug

#84 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  uimafit-parent/pom.xml
Labels: enhancement

#98 Use HTTPS instead of HTTP to resolve dependencies
  uimafit-parent/pom.xml
Labels: enhancement

#101 [UIMA-6223] Groovy plugin causes warning during build
  uimafit-parent/pom.xml
Labels: bug

#100 [UIMA-6222] XML-related unit test fails on Java 9+
  uimafit-core/src/test/java/org/apache/uima/fit/factory/AnalysisEngineFactoryTest.java
Labels: bug

#102 [UIMA-6224] uimaFIT does not build on Java 14
  uimafit-core/src/main/java/org/apache/uima/fit/factory/package-info.java
  uimafit-core/src/main/java/org/apache/uima/fit/util/package-info.java
  uimafit-parent/pom.xml
Labels: refactoring

#103 [UIMA-6226] uimaFIT maven plugin "generate" fails to import type systems from dependencies
  uimafit-maven-plugin/src/main/java/org/apache/uima/fit/maven/GenerateDescriptorsMojo.java
Labels: bug
