Repository apache/uima-uimafit, pull requests merged in 2020-11, with the labels that each got.

#131 [UIMA-6286] select following finds zero-width annotation at reference end position
  uimafit-core/src/main/java/org/apache/uima/fit/util/CasUtil.java
  uimafit-core/src/test/java/org/apache/uima/fit/util/JCasUtilTest.java
Labels: bug

#132 [UIMA-6288] select preceding using zero width anchor returns covering annotation
  uimafit-core/src/main/java/org/apache/uima/fit/util/CasUtil.java
  uimafit-core/src/test/java/org/apache/uima/fit/util/JCasUtilTest.java
Labels: bug

#133 [UIMA-6270] Add selectOverlapping to (J)CasUtil
  uimafit-core/src/main/java/org/apache/uima/fit/util/CasUtil.java
  uimafit-core/src/main/java/org/apache/uima/fit/util/JCasUtil.java
Labels: enhancement

#134 [UIMA-6292] selectCovering is slow
  uimafit-core/src/main/java/org/apache/uima/fit/util/CasUtil.java
Labels: bug

#135 [UIMA-6292] selectCovering is slow
  uimafit-core/src/main/java/org/apache/uima/fit/util/CasUtil.java
Labels: bug

#137 [UIMA-6270] Add selectOverlapping to (J)CasUtil
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/CasUtilBenchmark.java
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/JCasUtilBenchmark.java
  uimafit-core/src/main/java/org/apache/uima/fit/util/AnnotationPredicates.java
  uimafit-core/src/test/java/org/apache/uima/fit/util/AnnotationPredicatesTest.java
  uimafit-core/src/test/java/org/apache/uima/fit/util/CasUtilTest.java
  uimafit-core/src/test/java/org/apache/uima/fit/util/JCasUtilTest.java
  uimafit-core/src/test/java/org/apache/uima/fit/util/SelectionAssert.java
  uimafit-parent/pom.xml
Labels: enhancement

#136 [UIMA-6291] Improve uimaFIT benchmarking module
  uimafit-benchmark/pom.xml
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/Batch.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/Benchmark.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/BenchmarkGroup.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/CachingRandomJCasProvider.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/CasInitializationUtils.java
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/CasUtilBenchmark.java
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/JCasUtilBenchmark.java
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/SelectBenchmark.java
Labels: enhancement

#139 [UIMA-6291] Improve uimaFIT benchmarking module
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/Batch.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/Benchmark.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/BenchmarkGroup.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/CachingRandomJCasProvider.java
  uimafit-benchmark/src/main/java/org/apache/uima/fit/benchmark/CasInitializationUtils.java
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/FSUtilBenchmark.java
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/JCasFactoryBenchmark.java
  uimafit-benchmark/src/test/java/org/apache/uima/fit/benchmark/SelectBenchmark.java
Labels: enhancement

#140 [UIMA-6254] Move API report post-analysis script into the build resources
  uimafit-parent/pom.xml
  uimafit-parent/src/main/groovy/api-report.groovy
Labels: refactoring
